routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    if(Auth::check()){
        return view('home');
    }else{
        return view('Welcome');
    }
});

Auth::routes();

Route::resource('/libros',App\Http\Controllers\LibroController::class)->middleware('auth');
Route::resource('/categorias',App\Http\Controllers\CategoriaController::class)->middleware('auth');
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Libro.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * Class Libro
 *
 * @property $id
 * @property $nombre
 * @property $autor
 * @property $fechaPublicacion
 * @property $usuarioid
 * @property $categoriaid
 * @property $created_at
 * @property $updated_at
 *
 * @property Categoria $categoria
 * @property User $user
 * @package App
 * @mixin \Illuminate\Database\Eloquent\Builder
 */
class Libro extends Model
{

    static $rules = [
      'nombre' => 'required',
      'autor' => 'required',
      'fechaPublicacion' => 'required',
      'usuarioid',
  ];

  protected $perPage = 20;

    /**
     * Attributes that should be mass-assignable.
     *
     * @var array
     */
    protected $fillable = ['nombre','autor','fechaPublicacion','usuarioid','categoriaid'];


    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function categoria()
    {
        return $this->hasOne('App\Models\Categoria', 'id', 'categoriaid');
    }
    
    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function user()
    {
        return $this->hasOne('App\Models\User', 'id', 'usuarioid');
    }
    
    public function scopeName($query, $name){
        if($name)
            return $query->where('nombre', 'LIKE', "%$name%");
    }
}

app/Http/Controllers/LibroController.php
<?php

namespace App\Http\Controllers;

use App\Models\Libro;
use App\Models\User;
use App\Models\Categoria;
use Illuminate\Http\Request;

/**
 * Class LibroController
 * @package App\Http\Controllers
 */
class LibroController extends Controller
{
	/**
	 * Display a listing of the resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function index(Request $request)
	{
		$name  = $request->get('nombre');
		$libros = Libro::orderBy('nombre')
		->name($name)
		->paginate(5);

		return view('libro.index', compact('libros'))
		->with('i', (request()->input('page', 1) - 1) * $libros->perPage());
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function create()
	{
		$libro = new Libro();
		$usuarios = User::all();
		$categorias = Categoria::all();

		return view('libro.create', compact('libro','usuarios', 'categorias'));
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param  \Illuminate\Http\Request $request
	 * @return \Illuminate\Http\Response
	 */
	public function store(Request $request)
	{
		request()->validate(Libro::$rules);

		$libro = Libro::create($request->all());

		return redirect()->route('libros.index')
		->with('success', 'Libro created successfully.');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int $id
	 * @return \Illuminate\Http\Response
	 */
	public function show($id)
	{
		$libro = Libro::with('user','categoria')
		->find($id);
		return view('libro.show', compact('libro'));
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int $id
	 * @return \Illuminate\Http\Response
	 */
	public function edit($id)
	{
		$libro = Libro::find($id);
		$usuarios = User::all();
		$categorias = Categoria::all();
		return view('libro.edit', compact('libro','usuarios','categorias'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  \Illuminate\Http\Request $request
	 * @param  Libro $libro
	 * @return \Illuminate\Http\Response
	 */
	public function update(Request $request, Libro $libro)
	{
		request()->validate(Libro::$rules);

		$libro->update($request->all());

		return redirect()->route('libros.index')
		->with('success', 'Libro updated successfully');
	}

	/**
	 * @param int $id
	 * @return \Illuminate\Http\RedirectResponse
	 * @throws \Exception
	 */
	public function destroy($id)
	{
		$libro = Libro::find($id)->delete();

		return redirect()->route('libros.index')
		->with('success', 'Libro deleted successfully');
	}
}

resources/views/libro/create.blade.php
@extends('layouts.app')

@section('template_title')
    Create Libro
@endsection

@section('content')
    <section class="content container-fluid">
        <div class="row">
            <div class="col-md-12">

                @includeif('partials.errors')

                <div class="card card-default">
                    <div class="card-header">
                        <span class="card-title">Create Libro</span>
                    </div>
                    <div class="card-body">
                        <form method="POST" action="{{ route('libros.store') }}"  role="form" enctype="multipart/form-data">
                            @csrf

                            @include('libro.form')

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/libro/edit.blade.php
@extends('layouts.app')

@section('template_title')
    Update Libro
@endsection

@section('content')
    <section class="content container-fluid">
        <div class="">
            <div class="col-md-12">

                @includeif('partials.errors')

                <div class="card card-default">
                    <div class="card-header">
                        <span class="card-title">Update Libro</span>
                    </div>
                    <div class="card-body">
                        <form method="POST" action="{{ route('libros.update', $libro->id) }}"  role="form" enctype="multipart/form-data">
                            {{ method_field('PATCH') }}
                            @csrf

                            @include('libro.form')

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/libro/form.blade.php
<div class="box box-info padding-1">
    <div class="box-body">
        
        <div class="form-group">
            {{ Form::label('nombre') }}
            {{ Form::text('nombre', $libro->nombre, ['class' => 'form-control' . ($errors->has('nombre') ? ' is-invalid' : ''), 'placeholder' => 'Nombre']) }}
            {!! $errors->first('nombre', '<div class="invalid-feedback">:message</p>') !!}
        </div>
        <div class="form-group">
            {{ Form::label('autor') }}
            {{ Form::text('autor', $libro->autor, ['class' => 'form-control' . ($errors->has('autor') ? ' is-invalid' : ''), 'placeholder' => 'Autor']) }}
            {!! $errors->first('autor', '<div class="invalid-feedback">:message</p>') !!}
        </div>
        <div class="form-group">
            {{ Form::label('fecha Publicacion') }}
            {{ Form::date('fechaPublicacion', $libro->fechaPublicacion, ['class' => 'form-control' . ($errors->has('fechaPublicacion') ? ' is-invalid' : ''), 'placeholder' => 'Fechapublicacion']) }}
            {!! $errors->first('fechaPublicacion', '<div class="invalid-feedback">:message</p>') !!}
        </div>

        <label for="">Usuario prestado</label>
        <select name="usuarioid" id="usuarioid" class="form-control">
            <option value="">Ninguno</option>
            @foreach($usuarios as $usuario)
            <option value="{{$usuario->id}}">{{$usuario->name}}</option>
            @endforeach
        </select>
        <br/>
        <label for="">Categoria</label>
        <select name="categoriaid" id="categoriaid" class="form-control">
            @foreach($categorias as $categoria)
            <option value="{{$categoria->id}}">{{$categoria->nombre}}</option>
            @endforeach
        </select>
        <br/>
    </div>
    <div class="box-footer mt20">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</div>

resources/views/libro/index.blade.php
@extends('layouts.app')

@section('template_title')
Libro
@endsection

@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12">
            <div class="card">
                <div class="card-header">
                    <div style="display: flex; justify-content: space-between; align-items: center;">

                        <span id="card_title">
                            {{ __('Libro') }}
                        </span>

                        <div class="float-right">
                            <a href="{{ route('libros.create') }}" class="btn btn-primary btn-sm float-right"  data-placement="left">
                              {{ __('Create New') }}
                          </a>
                      </div>
                  </div>
              </div>
              @if ($message = Session::get('success'))
              <div class="alert alert-success">
                <p>{{ $message }}</p>
            </div>
            @endif

            <div class="card-body">
                <div class="table-responsive">
                    <span>Filtros</span>
                    <hr/>
                    {{ Form::open(['route' => 'libros.index', 'method' => 'GET', 'class' => 'form-inline pull-right']) }}
                    <div class="form-group" style="padding: 10px;">
                        {{ Form::text('nombre', null, ['class' => 'form-control', 'placeholder' => 'Nombre libro']) }}
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-default">
                            <span class="glyphicon glyphicon-search"></span>
                        </button>
                    </div>
                    {{ Form::close() }}
                    <br/>
                    
                    <table class="table table-striped table-hover">
                        <thead class="thead">
                            <tr>
                                <th>No</th>

                                <th>Nombre</th>
                                <th>Autor</th>
                                <th>Fecha publicacion</th>
                                <th>Usuario prestamo</th>
                                <th>Categoria</th>

                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($libros as $libro)
                            <tr>
                                <td>{{ ++$i }}</td>

                                <td>{{ $libro->nombre }}</td>
                                <td>{{ $libro->autor }}</td>
                                <td>{{ $libro->fechaPublicacion }}</td>
                                @if($libro->user != null)
                                    <td>{{ $libro->user->name}}</td>
                                @else
                                    <td>Disponible</td>
                                @endif
                                <td>{{ $libro->categoria->nombre }}</td>

                                <td>
                                    <form action="{{ route('libros.destroy',$libro->id) }}" method="POST">
                                        <a class="btn btn-sm btn-primary " href="{{ route('libros.show',$libro->id) }}"><i class="fa fa-fw fa-eye"></i> Show</a>
                                        <a class="btn btn-sm btn-success" href="{{ route('libros.edit',$libro->id) }}"><i class="fa fa-fw fa-edit"></i> Edit</a>
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn btn-danger btn-sm"><i class="fa fa-fw fa-trash"></i> Delete</button>
                                    </form>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        {!! $libros->links() !!}
    </div>
</div>
</div>
@endsection

resources/views/libro/show.blade.php
@extends('layouts.app')

@section('template_title')
    {{ $libro->name ?? 'Show Libro' }}
@endsection

@section('content')
    <section class="content container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="float-left">
                            <span class="card-title">Show Libro</span>
                        </div>
                        <div class="float-right">
                            <a class="btn btn-primary" href="{{ route('libros.index') }}"> Back</a>
                        </div>
                    </div>

                    <div class="card-body">
                        
                        <div class="form-group">
                            <strong>Nombre:</strong>
                            {{ $libro->nombre }}
                        </div>
                        <div class="form-group">
                            <strong>Autor:</strong>
                            {{ $libro->autor }}
                        </div>
                        <div class="form-group">
                            <strong>Fechapublicacion:</strong>
                            {{ $libro->fechaPublicacion }}
                        </div>
                        <div class="form-group">
                            <strong>Usuario:</strong>
                            @if($libro->user != null)
                                {{ $libro->user->name }}
                            @else
                                <span>Disponible</span>
                            @endif
                        </div>
                        <div class="form-group">
                            <strong>Categoria:</strong>
                            {{ $libro->categoria->nombre }}
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection